/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__test_prompt__0_0_1 = never;
export type PromptConfig__test_prompt__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__test_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__test_prompt__0_0_1;
  variables: PromptVariables__test_prompt__0_0_1;
  content: string;
};
export type Prompt__test_prompt = {
  name: 'Test prompt';
  slug: 'test-prompt';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__test_prompt__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    'test-prompt': Prompt__test_prompt;
  };
  globals: Globals;
};
