/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type Globals = {};
export type Agency = {
  prompts: {};
  globals: Globals;
};
